# -*- coding: utf-8 -*-
"""Ass2_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmJv8BDdoAbBM-7ho7iCDAk64ug4iPMd
"""

import random
import copy
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

ZONES = {
    'Z1': {'name': 'Heavy Item Floor Storage',          'capacity': 120},
    'Z2': {'name': 'Standard Rack Storage',             'capacity': 80},
    'Z3': {'name': 'Fragile Item Shelf',                'capacity': 80},
    'Z4': {'name': 'Temperature Controlled Storage',    'capacity': 80},
    'Z5': {'name': 'Hazardous Material Storage',        'capacity': 80},
    'Z6': {'name': 'Fast-Moving Product Area',          'capacity': 60},
    'Z7': {'name': 'Bulk Dry Storage',                  'capacity': 150},
    'Z8': {'name': 'Refrigerated Loading Dock',         'capacity': 100},
}

ZONE_KEYS = list(ZONES.keys())

PRODUCTS = [
    {'id': 'P1',  'name': 'Glass Bottles',     'weight': 20, 'category': 'Beverage',    'fragile': True,  'hazardous': False, 'temp_ctrl': False, 'demand': 'Medium'},
    {'id': 'P2',  'name': 'Frozen Meat',        'weight': 30, 'category': 'Food',        'fragile': False, 'hazardous': False, 'temp_ctrl': True,  'demand': 'High'},
    {'id': 'P3',  'name': 'Cleaning Acid',      'weight': 10, 'category': 'Chemical',   'fragile': False, 'hazardous': True,  'temp_ctrl': False, 'demand': 'Low'},
    {'id': 'P4',  'name': 'Rice Bags',          'weight': 50, 'category': 'Grocery',    'fragile': False, 'hazardous': False, 'temp_ctrl': False, 'demand': 'High'},
    {'id': 'P5',  'name': 'Ceramic Plates',     'weight': 15, 'category': 'Kitchenware','fragile': True,  'hazardous': False, 'temp_ctrl': False, 'demand': 'Medium'},
    {'id': 'P6',  'name': 'Ice Cream',          'weight': 25, 'category': 'Food',        'fragile': False, 'hazardous': False, 'temp_ctrl': True,  'demand': 'High'},
    {'id': 'P7',  'name': 'Detergent',          'weight': 12, 'category': 'Chemical',   'fragile': False, 'hazardous': True,  'temp_ctrl': False, 'demand': 'Medium'},
    {'id': 'P8',  'name': 'Chips Carton',       'weight':  8, 'category': 'Snacks',     'fragile': False, 'hazardous': False, 'temp_ctrl': False, 'demand': 'High'},
    {'id': 'P9',  'name': 'Olive Oil Bottles',  'weight': 18, 'category': 'Grocery',    'fragile': True,  'hazardous': False, 'temp_ctrl': False, 'demand': 'Medium'},
    {'id': 'P10', 'name': 'Industrial Bleach',  'weight': 22, 'category': 'Chemical',   'fragile': False, 'hazardous': True,  'temp_ctrl': False, 'demand': 'Low'},
    {'id': 'P11', 'name': 'Yogurt Cartons',     'weight': 14, 'category': 'Food',        'fragile': False, 'hazardous': False, 'temp_ctrl': True,  'demand': 'High'},
    {'id': 'P12', 'name': 'Flour Bags',         'weight': 45, 'category': 'Grocery',    'fragile': False, 'hazardous': False, 'temp_ctrl': False, 'demand': 'High'},
    {'id': 'P13', 'name': 'Wine Bottles',       'weight': 16, 'category': 'Beverage',   'fragile': True,  'hazardous': False, 'temp_ctrl': False, 'demand': 'Medium'},
    {'id': 'P14', 'name': 'Paint Cans',         'weight': 28, 'category': 'Chemical',   'fragile': False, 'hazardous': True,  'temp_ctrl': False, 'demand': 'Low'},
    {'id': 'P15', 'name': 'Biscuit Boxes',      'weight':  6, 'category': 'Snacks',     'fragile': False, 'hazardous': False, 'temp_ctrl': False, 'demand': 'High'},
    {'id': 'P16', 'name': 'Motor Oil',          'weight': 35, 'category': 'Chemical',   'fragile': False, 'hazardous': True,  'temp_ctrl': False, 'demand': 'Low'},
    {'id': 'P17', 'name': 'Frozen Fish',        'weight': 20, 'category': 'Food',        'fragile': False, 'hazardous': False, 'temp_ctrl': True,  'demand': 'High'},
    {'id': 'P18', 'name': 'Bubble Wrap Rolls',  'weight': 10, 'category': 'Packaging',  'fragile': True,  'hazardous': False, 'temp_ctrl': False, 'demand': 'Medium'},
    {'id': 'P19', 'name': 'Wheat Sacks',        'weight': 40, 'category': 'Grocery',    'fragile': False, 'hazardous': False, 'temp_ctrl': False, 'demand': 'High'},
    {'id': 'P20', 'name': 'Hand Sanitizer',     'weight':  8, 'category': 'Chemical',   'fragile': True,  'hazardous': False, 'temp_ctrl': False, 'demand': 'Medium'},
]

NUM_PRODUCTS = len(PRODUCTS)

FRAGILE_IDX    = {i for i, p in enumerate(PRODUCTS) if p['fragile']}
HAZARDOUS_IDX  = {i for i, p in enumerate(PRODUCTS) if p['hazardous']}
TEMP_IDX       = {i for i, p in enumerate(PRODUCTS) if p['temp_ctrl']}
HIGH_DEMAND_IDX= {i for i, p in enumerate(PRODUCTS) if p['demand'] == 'High'}
HEAVY_IDX      = {i for i, p in enumerate(PRODUCTS) if p['weight'] > 40}
Z8_ELIGIBLE_IDX= {i for i, p in enumerate(PRODUCTS) if p['temp_ctrl'] and p['demand'] == 'High'}
FOOD_IDX       = {i for i, p in enumerate(PRODUCTS) if p['category'] == 'Food'}
CHEMICAL_IDX   = {i for i, p in enumerate(PRODUCTS) if p['category'] == 'Chemical'}

PEN_WEIGHT_PER_KG  = 2
PEN_FRAGILE        = 8
PEN_HAZARDOUS      = 10
PEN_TEMP           = 9
PEN_HIGH_DEMAND    = 5
PEN_HEAVY          = 4
PEN_CATEGORY_PAIR  = 3
PEN_FOOD_CHEM_PAIR = 15
PEN_Z8_INELIGIBLE  = 12


def fitness(chromosome):
    """Lower is better. Returns (total_penalty, violation_details)."""
    penalty = 0
    violations = []

    # Zone weight capacity
    zone_weight = {z: 0 for z in ZONE_KEYS}
    for i, zone in enumerate(chromosome):
        zone_weight[zone] += PRODUCTS[i]['weight']

    for zone, total in zone_weight.items():
        cap = ZONES[zone]['capacity']
        if total > cap:
            excess = total - cap
            p = excess * PEN_WEIGHT_PER_KG
            penalty += p
            violations.append(f"[Weight] {zone} over capacity by {excess} kg → +{p}")

    # Fragile products must be in Z3
    for i in FRAGILE_IDX:
        if chromosome[i] != 'Z3':
            penalty += PEN_FRAGILE
            violations.append(f"[Fragile] {PRODUCTS[i]['name']} in {chromosome[i]} (must be Z3) → +{PEN_FRAGILE}")

    # Hazardous must be in Z5
    for i in HAZARDOUS_IDX:
        if chromosome[i] != 'Z5':
            penalty += PEN_HAZARDOUS
            violations.append(f"[Hazardous] {PRODUCTS[i]['name']} in {chromosome[i]} (must be Z5) → +{PEN_HAZARDOUS}")

    # Temperature-sensitive must be in Z4 or Z8
    for i in TEMP_IDX:
        if chromosome[i] not in ('Z4', 'Z8'):
            penalty += PEN_TEMP
            violations.append(f"[Temp] {PRODUCTS[i]['name']} in {chromosome[i]} (must be Z4/Z8) → +{PEN_TEMP}")

    # High-demand items should be in Z6
    for i in HIGH_DEMAND_IDX:
        if chromosome[i] != 'Z6':
            penalty += PEN_HIGH_DEMAND
            violations.append(f"[HighDemand] {PRODUCTS[i]['name']} in {chromosome[i]} (should be Z6) → +{PEN_HIGH_DEMAND}")

    # Heavy items (>40 kg) must be in Z1
    for i in HEAVY_IDX:
        if chromosome[i] != 'Z1':
            penalty += PEN_HEAVY
            violations.append(f"[Heavy] {PRODUCTS[i]['name']} ({PRODUCTS[i]['weight']} kg) in {chromosome[i]} (must be Z1) → +{PEN_HEAVY}")

    # Category compatibility (same-category items in different zones)
    categories = {}
    for i, zone in enumerate(chromosome):
        cat = PRODUCTS[i]['category']
        categories.setdefault(cat, {}).setdefault(zone, []).append(i)

    for cat, zone_map in categories.items():
        zones_used = list(zone_map.keys())
        for a in range(len(zones_used)):
            for b in range(a + 1, len(zones_used)):
                pairs = len(zone_map[zones_used[a]]) * len(zone_map[zones_used[b]])
                p = pairs * PEN_CATEGORY_PAIR
                penalty += p
                violations.append(f"[Compat] {cat}: products split between {zones_used[a]} & {zones_used[b]} ({pairs} pairs) → +{p}")

    # Food & Chemical must not share a zone
    zone_products = {z: [] for z in ZONE_KEYS}
    for i, zone in enumerate(chromosome):
        zone_products[zone].append(i)

    for zone, prods in zone_products.items():
        food_in_zone  = [i for i in prods if i in FOOD_IDX]
        chem_in_zone  = [i for i in prods if i in CHEMICAL_IDX]
        pairs = len(food_in_zone) * len(chem_in_zone)
        if pairs > 0:
            p = pairs * PEN_FOOD_CHEM_PAIR
            penalty += p
            violations.append(f"[FoodChem] {zone} has {len(food_in_zone)} food & {len(chem_in_zone)} chem products ({pairs} pairs) → +{p}")

    # Z8 restriction
    for i in zone_products['Z8']:
        if i not in Z8_ELIGIBLE_IDX:
            penalty += PEN_Z8_INELIGIBLE
            violations.append(f"[Z8] {PRODUCTS[i]['name']} not eligible for Z8 → +{PEN_Z8_INELIGIBLE}")

    return penalty, violations


def random_chromosome():
    """Generate a random valid-ish chromosome (soft-biased toward correct zones)."""
    chrom = []
    for i in range(NUM_PRODUCTS):
        p = PRODUCTS[i]
        if p['fragile'] and p['hazardous']:
            zone = random.choice(['Z3', 'Z5'])
        elif p['fragile']:
            zone = 'Z3'
        elif p['hazardous']:
            zone = 'Z5'
        elif p['temp_ctrl']:
            zone = random.choice(['Z4', 'Z8'])
        elif p['weight'] > 40:
            zone = 'Z1'
        else:
            zone = random.choice(ZONE_KEYS)
        chrom.append(zone)
    return chrom


def tournament_selection(population, fitnesses, k=3):
    """Select one individual via tournament of size k."""
    contestants = random.sample(range(len(population)), k)
    winner = min(contestants, key=lambda idx: fitnesses[idx])
    return copy.copy(population[winner])


def two_point_crossover(parent1, parent2):
    p1, p2 = sorted(random.sample(range(NUM_PRODUCTS), 2))
    child1 = parent1[:p1] + parent2[p1:p2] + parent1[p2:]
    child2 = parent2[:p1] + parent1[p1:p2] + parent2[p2:]
    return child1, child2


def mutate(chromosome, mutation_rate=0.05):
    """Randomly reassign zones for each gene with probability mutation_rate."""
    chrom = chromosome[:]
    for i in range(NUM_PRODUCTS):
        if random.random() < mutation_rate:
            chrom[i] = random.choice(ZONE_KEYS)
    return chrom


def genetic_algorithm(
    pop_size=100,
    max_generations=300,
    crossover_rate=0.8,
    mutation_rate=0.05,
    tournament_k=3,
    elitism=2
):
    population = [random_chromosome() for _ in range(pop_size)]
    fitnesses  = [fitness(c)[0] for c in population]

    best_chrom    = copy.copy(population[fitnesses.index(min(fitnesses))])
    best_fitness  = min(fitnesses)
    best_gen      = 0

    print(f"{'Generation':>12} | {'Best Fitness':>14} | {'Avg Fitness':>12}")
    print("-" * 46)

    for gen in range(1, max_generations + 1):
        new_population = []

        # Elitism carry top individuals unchanged
        sorted_idx = sorted(range(pop_size), key=lambda x: fitnesses[x])
        for e in range(elitism):
            new_population.append(copy.copy(population[sorted_idx[e]]))

        # Fill rest of new population
        while len(new_population) < pop_size:
            p1 = tournament_selection(population, fitnesses, tournament_k)
            p2 = tournament_selection(population, fitnesses, tournament_k)

            if random.random() < crossover_rate:
                c1, c2 = two_point_crossover(p1, p2)
            else:
                c1, c2 = copy.copy(p1), copy.copy(p2)

            c1 = mutate(c1, mutation_rate)
            c2 = mutate(c2, mutation_rate)

            new_population.append(c1)
            if len(new_population) < pop_size:
                new_population.append(c2)

        population = new_population
        fitnesses  = [fitness(c)[0] for c in population]

        gen_best = min(fitnesses)
        gen_avg  = sum(fitnesses) / len(fitnesses)

        if gen_best < best_fitness:
            best_fitness = gen_best
            best_chrom   = copy.copy(population[fitnesses.index(gen_best)])
            best_gen     = gen

        if gen % 50 == 0 or gen_best == 0:
            print(f"{gen:>12} | {gen_best:>14} | {gen_avg:>12.2f}")

        if best_fitness == 0:
            print(f"\n✓ Perfect solution found at generation {gen}!")
            break

    return best_chrom, best_fitness, gen, best_gen


def display_results(chromosome, best_fitness, generations_run, best_gen):
    print("\n" + "=" * 60)
    print("           OPTIMAL WAREHOUSE STORAGE PLAN")
    print("=" * 60)

    zone_assignment = {z: [] for z in ZONE_KEYS}
    for i, zone in enumerate(chromosome):
        zone_assignment[zone].append(PRODUCTS[i]['name'])

    for zone in ZONE_KEYS:
        products_in_zone = zone_assignment[zone]
        zone_name = ZONES[zone]['name']
        cap       = ZONES[zone]['capacity']
        weight    = sum(PRODUCTS[i]['weight'] for i, z in enumerate(chromosome) if z == zone)
        if products_in_zone:
            print(f"\n{zone} – {zone_name} (Capacity: {cap} kg | Used: {weight} kg)")
            for prod in products_in_zone:
                print(f"   • {prod}")
        else:
            print(f"\n{zone} – {zone_name} → (empty)")

    print("\n" + "=" * 60)
    print(f"  Best Fitness Score : {best_fitness}")
    print(f"  Generations Run    : {generations_run}")
    print(f"  Best Found at Gen  : {best_gen}")
    print("=" * 60)

    _, violations = fitness(chromosome)
    if violations:
        print(f"\n  Remaining Violations ({len(violations)}):")
        for v in violations:
            print(f"\t{v}")
    else:
        print("\n No constraint violations!")


def export_to_excel(chromosome, best_fitness, generations_run, filename="warehouse_optimization.xlsx"):
    wb = Workbook()

    # ── Sheet 1: Storage Plan ─────────────────
    ws1 = wb.active
    ws1.title = "Storage Plan"

    header_font  = Font(name='Arial', bold=True, color='FFFFFF', size=11)
    header_fill  = PatternFill('solid', start_color='2E4057')
    zone_fill    = PatternFill('solid', start_color='D6EAF8')
    alt_fill     = PatternFill('solid', start_color='EBF5FB')
    center_align = Alignment(horizontal='center', vertical='center')
    left_align   = Alignment(horizontal='left',   vertical='center')
    thin_border  = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'),  bottom=Side(style='thin')
    )

    headers = ['Zone', 'Zone Name', 'Capacity (kg)', 'Used (kg)', 'Products Stored', 'Status']
    col_widths = [8, 35, 15, 12, 60, 12]

    for col, (h, w) in enumerate(zip(headers, col_widths), 1):
        cell = ws1.cell(row=1, column=col, value=h)
        cell.font      = header_font
        cell.fill      = header_fill
        cell.alignment = center_align
        cell.border    = thin_border
        ws1.column_dimensions[cell.column_letter].width = w

    ws1.row_dimensions[1].height = 20

    zone_assignment = {z: [] for z in ZONE_KEYS}
    for i, zone in enumerate(chromosome):
        zone_assignment[zone].append(PRODUCTS[i]['name'])

    for row_idx, zone in enumerate(ZONE_KEYS, 2):
        products_in_zone = zone_assignment[zone]
        cap    = ZONES[zone]['capacity']
        weight = sum(PRODUCTS[i]['weight'] for i, z in enumerate(chromosome) if z == zone)
        status = 'OK' if weight <= cap else 'OVER CAPACITY'
        s_font_color = 'FF0000' if status == 'OVER CAPACITY' else '1E8449'

        fill = zone_fill if row_idx % 2 == 0 else alt_fill

        values = [zone, ZONES[zone]['name'], cap, weight,
                  ', '.join(products_in_zone) if products_in_zone else '(empty)', status]

        for col, val in enumerate(values, 1):
            cell = ws1.cell(row=row_idx, column=col, value=val)
            cell.fill   = fill
            cell.border = thin_border
            cell.font   = Font(name='Arial', size=10,
                               color=s_font_color if col == 6 else '000000',
                               bold=(col == 6))
            cell.alignment = center_align if col in (1, 3, 4, 6) else left_align

    # Summary row
    sum_row = len(ZONE_KEYS) + 2
    ws1.cell(row=sum_row, column=1, value='SUMMARY').font = Font(bold=True, name='Arial')
    ws1.cell(row=sum_row, column=4, value=f'Total: {sum(p["weight"] for p in PRODUCTS)} kg').font = Font(bold=True, name='Arial')
    ws1.cell(row=sum_row, column=6, value=f'Best Fitness: {best_fitness}').font = Font(bold=True, name='Arial', color='C0392B' if best_fitness > 0 else '1E8449')

    # ── Sheet 2: Product Details ──────────────
    ws2 = wb.create_sheet("Product Details")
    prod_headers = ['Product ID', 'Product Name', 'Weight (kg)', 'Category',
                    'Fragile', 'Hazardous', 'Temp Ctrl', 'Demand', 'Assigned Zone', 'Zone Name']
    prod_widths  = [12, 22, 13, 14, 9, 11, 11, 10, 14, 35]

    for col, (h, w) in enumerate(zip(prod_headers, prod_widths), 1):
        cell = ws2.cell(row=1, column=col, value=h)
        cell.font      = header_font
        cell.fill      = header_fill
        cell.alignment = center_align
        cell.border    = thin_border
        ws2.column_dimensions[cell.column_letter].width = w

    for row_idx, (i, product) in enumerate(enumerate(PRODUCTS), 2):
        assigned_zone = chromosome[i]
        fill = zone_fill if row_idx % 2 == 0 else alt_fill
        values = [
            product['id'], product['name'], product['weight'], product['category'],
            'Yes' if product['fragile']   else 'No',
            'Yes' if product['hazardous'] else 'No',
            'Yes' if product['temp_ctrl'] else 'No',
            product['demand'], assigned_zone, ZONES[assigned_zone]['name']
        ]
        for col, val in enumerate(values, 1):
            cell = ws2.cell(row=row_idx, column=col, value=val)
            cell.fill      = fill
            cell.border    = thin_border
            cell.alignment = center_align if col != 2 else left_align
            cell.font      = Font(name='Arial', size=10)

    # ── Sheet 3: Violations ───────────────────
    ws3 = wb.create_sheet("Violations")
    _, violations = fitness(chromosome)

    ws3.cell(row=1, column=1, value='Constraint Violations Report').font = Font(bold=True, size=13, name='Arial')
    ws3.cell(row=2, column=1, value=f'Total violations: {len(violations)}  |  Best fitness score: {best_fitness}').font = Font(size=11, name='Arial')

    vio_headers = ['#', 'Violation Description']
    for col, h in enumerate(vio_headers, 1):
        cell = ws3.cell(row=4, column=col, value=h)
        cell.font      = header_font
        cell.fill      = header_fill
        cell.alignment = center_align
        cell.border    = thin_border

    ws3.column_dimensions['A'].width = 6
    ws3.column_dimensions['B'].width = 90

    if violations:
        for row_idx, vio in enumerate(violations, 5):
            ws3.cell(row=row_idx, column=1, value=row_idx - 4).font = Font(name='Arial', size=10)
            cell = ws3.cell(row=row_idx, column=2, value=vio)
            cell.font      = Font(name='Arial', size=10, color='C0392B')
            cell.border    = thin_border
    else:
        ws3.cell(row=5, column=2, value='✓ No violations – all constraints satisfied!').font = Font(
            name='Arial', size=11, bold=True, color='1E8449')

    wb.save(filename)
    print(f"\n  Excel report saved → {filename}")


if __name__ == '__main__':
    POPULATION_SIZE  = 150
    MAX_GENERATIONS  = 500
    CROSSOVER_RATE   = 0.85
    MUTATION_RATE    = 0.24
    TOURNAMENT_K     = 7
    ELITISM          = 5

    print("=" * 60)
    print("   WAREHOUSE STORAGE OPTIMIZATION — GENETIC ALGORITHM")
    print("=" * 60)
    print(f"  Population size  : {POPULATION_SIZE}")
    print(f"  Max generations  : {MAX_GENERATIONS}")
    print(f"  Crossover rate   : {CROSSOVER_RATE}")
    print(f"  Mutation rate    : {MUTATION_RATE}")
    print(f"  Tournament size  : {TOURNAMENT_K}")
    print(f"  Elitism count    : {ELITISM}")
    print("=" * 60 + "\n")

    best_chrom, best_fitness, generations_run, best_gen = genetic_algorithm(
        pop_size=POPULATION_SIZE,
        max_generations=MAX_GENERATIONS,
        crossover_rate=CROSSOVER_RATE,
        mutation_rate=MUTATION_RATE,
        tournament_k=TOURNAMENT_K,
        elitism=ELITISM
    )

    display_results(best_chrom, best_fitness, generations_run, best_gen)

    # Bonus: export to Excel
    export_to_excel(best_chrom, best_fitness, generations_run,
                    filename="warehouse_optimization.xlsx")